### ISSUE TITLE
Does not run on windows 10

### ISSUE THREAD

**Issue by byteatom** [knightedcodemonkey/duel#48]
Nodejs: v20.12.2

Error when running duel: 
Failed to compile: spawn D:\project\xxxx\node_modules\.bin\tsc ENOENT

Adding "shell: true" to the option of the spawn() function call in duel.js seems to solve the problem.

**Comment by knightedcodemonkey** [comment]
Hi @byteatom thanks for reporting this. Did you want to open a PR?

**Comment by davidensinger** [comment]
I also ran into this issue with version 1.0.8 and can confirm that adding `shell: true` to the options argument of spawn fixes it. I would be happy to submit a PR, but am curious about the timeline for the next major version of 2.0.0. How stable is 2.0.0-rc.1? I branched off main and was a little surprised when I realized there was a release candidate out there. Is there any interest in releasing a fix as 1.0.9? Of course, the issue is present in 2.0.0-rc.1 too, so if the plan is to publish a 2.0.0 soon I would just make my PR against main as-is. Just let me know and thank you for your work on this.
